### PR TITLE
Fix not switching workstation from panel button

### PR DESCRIPTION
**Pull request by rotech**
As suggested, this is now done by passing the whole ws object, and checking the number.  Tested, and working really well.

I'm not strong with c, so please check my string handling.

### CODE REVIEW

**Comment by ldelossa** [comment]
@rotech 

One thing I do not quite understand is whether this is truly necessary or not. For example:

```
🖳  swaymsg workspace 12    

~
🖳  swaymsg workspace number 12

~
🖳  swaymsg workspace 12   
```

If you run those commands on your machine, don't both commands work appropriately? 
Can you run `swaymsg -t get_workspaces --raw` ? In your case, we shouldn't see a 'name' field at all if this is not working for you.

**Comment by ldelossa** [comment]
@rotech regardless of the above, I pushed a fixup commit which changes a bit of how the `sway_client_ipc_focus_workspace` function was refactored. 

I'm going to assume its "most correct" to provide `ws->num` and not `ws->name` when the command is "workspace number".

**Comment by rotech** [comment]
@ldelossa 
Files attached with the unpatched way-shell before, and then after clicking the workspace button.  You can see that instead of switching to the clicked workspace it creates a new identical workspace, but with a different ID.
[after_switch.txt](https://github.com/ldelossa/way-shell/files/14474327/after_switch.txt)
[before_switch.txt](https://github.com/ldelossa/way-shell/files/14474328/before_switch.txt)

The issue is when you name a workspace like "12:Browser" it has special meaning in sway.  Not respecting the numbers before the ':' also causes ordering issues in way-shell meaning commands like workspace prev | next don't follow the same order as displayed in the panel.

I will test your changes as soon as I get a chance, and let you know.
Thanks.

**Comment by ldelossa** [comment]
Understood @rotech and thanks for the explanation. 

Yes if you can confirm the change works. Im making a bit of an assumption that only the number value is necessary in the "workspace number" command, and not the full name. This seems logical to me but if you know otherwise or it gives you issue when testing ill drop that commit.

**Comment by ldelossa** [comment]
Hey @rotech - not to be a pest but I tend to avoid merge commits when possible. Is it okay to rebase the changes from MAIN to this PR instead of creating the merge commit?

**Comment by rotech** [comment]
@ldelossa, your fix works perfectly.  And yeah, no problem to rebase, do you want me to open a new PR with the changes rebased into the main branch?  I have done that on my repo, but I'm not sure how to change this PR to that.

**Pull request closed without merging**
